// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartE_faceCartesian_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 0.0000, 40.0000 ],
	[ 10.0000, 40.0000 ],
	[ 20.0000, 20.0000 ],
	[ 30.0000, 40.0000 ],
	[ 40.0000, 40.0000 ],
	[ 50.0000, 20.0000 ],
	[ 60.0000, 40.0000 ],
	[ 70.0000, 40.0000 ],
	[ 80.0000, 20.0000 ],
	[ 90.0000, 40.0000 ],
	[ 100.0000, 40.0000 ],
	[ 110.0000, 20.0000 ],
	[ 120.0000, 40.0000 ],
	[ 130.0000, 40.0000 ],
	[ 140.0000, 20.0000 ],
	[ 150.0000, 40.0000 ],
	[ 160.0000, 40.0000 ],
	[ 170.0000, 20.0000 ],
	[ 180.0000, 40.0000 ],
	[ 190.0000, 40.0000 ],
	[ 200.0000, 20.0000 ],
	[ 210.0000, 40.0000 ],
	[ 220.0000, 40.0000 ],
	[ 230.0000, 20.0000 ],
	[ 240.0000, 40.0000 ],
	[ 250.0000, 40.0000 ],
	[ 250.0000, 0.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_myPartE_faceCartesian_Fa000 = ctr_face_fig_myPartE_faceCartesian_Fa000_Ctr000;
fig_myPartE_faceCartesian = face_fig_myPartE_faceCartesian_Fa000;
const ctr_face_fig_myPartE_facePolarAbs_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 0.0000 ],
	[ 28.2843, 28.2843 ],
	[ 14.1421, 14.1421 ],
	[ 0.0000, 40.0000 ],
	[ 0.0000, 20.0000 ],
	[ -28.2843, 28.2843 ],
	[ -14.1421, 14.1421 ],
	[ -40.0000, 0.0000 ],
	[ -20.0000, 0.0000 ],
	[ -28.2843, -28.2843 ],
	[ -14.1421, -14.1421 ],
	[ -0.0000, -40.0000 ],
	[ -0.0000, -20.0000 ],
	[ 28.2843, -28.2843 ],
	[ 14.1421, -14.1421 ],
	[ 40.0000, 0.0000 ],
	[ 20.0000, 0.0000 ] ] });

face_fig_myPartE_facePolarAbs_Fa000 = ctr_face_fig_myPartE_facePolarAbs_Fa000_Ctr000;
fig_myPartE_facePolarAbs = face_fig_myPartE_facePolarAbs_Fa000;
const ctr_face_fig_myPartE_facePolarRel_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 10.0000, 17.3205 ],
	[ 25.3209, 30.1763 ],
	[ 44.1147, 37.0167 ],
	[ 64.1147, 37.0167 ],
	[ 82.9086, 30.1763 ],
	[ 98.2295, 17.3205 ],
	[ 108.2295, 0.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_myPartE_facePolarRel_Fa000 = ctr_face_fig_myPartE_facePolarRel_Fa000_Ctr000;
fig_myPartE_facePolarRel = face_fig_myPartE_facePolarRel_Fa000;

const subpax_myPartE_cartesian =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartE_faceCartesian )
		)
	);


const subpax_myPartE_polarAbs =
	translate( [ 0, 0, 100, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartE_facePolarAbs )
		)
	);


const subpax_myPartE_polarRel =
	translate( [ 0, 0, 200, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartE_facePolarRel )
		)
	);

const pax_myPartE = union( subpax_myPartE_cartesian, subpax_myPartE_polarAbs, subpax_myPartE_polarRel );

return pax_myPartE;
}
module.exports = { main };
