// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartF_faceCorners_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 190.0000, 0.0000 ],
	[ 191.9509, 0.1921 ],
	[ 193.8268, 0.7612 ],
	[ 195.5557, 1.6853 ],
	[ 197.0711, 2.9289 ],
	[ 198.3147, 4.4443 ],
	[ 199.2388, 6.1732 ],
	[ 199.8079, 8.0491 ],
	[ 200.0000, 10.0000 ],
	[ 200.0000, 100.0000 ],
	[ 10.0000, 100.0000 ],
	[ 8.2635, 99.8481 ],
	[ 6.5798, 99.3969 ],
	[ 5.0000, 98.6603 ],
	[ 3.5721, 97.6604 ],
	[ 2.3396, 96.4279 ],
	[ 1.3397, 95.0000 ],
	[ 0.6031, 93.4202 ],
	[ 0.1519, 91.7365 ],
	[ 0.0000, 90.0000 ],
	[ 0.0000, 0.0000 ] ] });

const ctr_face_fig_myPartF_faceCorners_Fa000_Ctr001 = polygon({ points: [ [ 47.4755, 20.0000 ],
	[ 83.3333, 20.0000 ],
	[ 85.2842, 20.1921 ],
	[ 87.1602, 20.7612 ],
	[ 88.8890, 21.6853 ],
	[ 90.4044, 22.9289 ],
	[ 91.6480, 24.4443 ],
	[ 92.5721, 26.1732 ],
	[ 93.1412, 28.0491 ],
	[ 93.3333, 30.0000 ],
	[ 93.3333, 65.8579 ],
	[ 94.5770, 67.3732 ],
	[ 95.5011, 69.1021 ],
	[ 96.0701, 70.9780 ],
	[ 96.2623, 72.9289 ],
	[ 96.0701, 74.8798 ],
	[ 95.5011, 76.7558 ],
	[ 94.5770, 78.4846 ],
	[ 93.3333, 80.0000 ],
	[ 91.8180, 81.2436 ],
	[ 90.0891, 82.1677 ],
	[ 88.2132, 82.7368 ],
	[ 86.2623, 82.9289 ],
	[ 84.3114, 82.7368 ],
	[ 82.4354, 82.1677 ],
	[ 80.7066, 81.2436 ],
	[ 79.1912, 80.0000 ],
	[ 43.3333, 80.0000 ],
	[ 41.3824, 79.8079 ],
	[ 39.5065, 79.2388 ],
	[ 37.7776, 78.3147 ],
	[ 36.2623, 77.0711 ],
	[ 35.0186, 75.5557 ],
	[ 34.0945, 73.8268 ],
	[ 33.5255, 71.9509 ],
	[ 33.3333, 70.0000 ],
	[ 33.3333, 34.1421 ],
	[ 32.0897, 32.6268 ],
	[ 31.1656, 30.8979 ],
	[ 30.5965, 29.0220 ],
	[ 30.4044, 27.0711 ],
	[ 30.5965, 25.1202 ],
	[ 31.1656, 23.2442 ],
	[ 32.0897, 21.5154 ],
	[ 33.3333, 20.0000 ],
	[ 34.8487, 18.7564 ],
	[ 36.5776, 17.8323 ],
	[ 38.4535, 17.2632 ],
	[ 40.4044, 17.0711 ],
	[ 42.3553, 17.2632 ],
	[ 44.2312, 17.8323 ],
	[ 45.9601, 18.7564 ],
	[ 47.4755, 20.0000 ] ] });

const ctr_face_fig_myPartF_faceCorners_Fa000_Ctr002 = polygon({ points: [ [ 126.6667, 20.0000 ],
	[ 166.6667, 20.0000 ],
	[ 146.6667, 80.0000 ],
	[ 126.6667, 20.0000 ] ] });

face_fig_myPartF_faceCorners_Fa000 = subtract( ctr_face_fig_myPartF_faceCorners_Fa000_Ctr000, ctr_face_fig_myPartF_faceCorners_Fa000_Ctr001, ctr_face_fig_myPartF_faceCorners_Fa000_Ctr002 );
fig_myPartF_faceCorners = face_fig_myPartF_faceCorners_Fa000;

const subpax_myPartF_corners =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 50}, fig_myPartF_faceCorners )
		)
	);

const pax_myPartF = subpax_myPartF_corners;

return pax_myPartF;
}
module.exports = { main };
