// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartH_faceCircle_Fa000_Ctr000 = polygon({ points: [ [ 298.4000, 0.0000 ],
	[ 298.4000, -100.0000 ],
	[ 328.4000, -40.0000 ],
	[ 358.4000, -100.0000 ],
	[ 358.4000, 0.0000 ],
	[ 445.0025, 50.0000 ],
	[ 378.0410, 45.9808 ],
	[ 415.0025, 101.9615 ],
	[ 328.4000, 51.9615 ],
	[ 241.7975, 101.9615 ],
	[ 278.7590, 45.9808 ],
	[ 211.7975, 50.0000 ],
	[ 298.4000, 0.0000 ] ] });

face_fig_myPartH_faceCircle_Fa000 = ctr_face_fig_myPartH_faceCircle_Fa000_Ctr000;
fig_myPartH_faceCircle = face_fig_myPartH_faceCircle_Fa000;
const ctr_face_fig_myPartH_faceLine_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 0.0000, -10.0000 ],
	[ 0.0000, -110.0000 ],
	[ 30.0000, -50.0000 ],
	[ 60.0000, -110.0000 ],
	[ 60.0000, -10.0000 ],
	[ 100.0000, -10.0000 ],
	[ 100.0000, -130.0000 ],
	[ 136.0000, -58.0000 ],
	[ 172.0000, -130.0000 ],
	[ 172.0000, -10.0000 ],
	[ 212.0000, -10.0000 ],
	[ 212.0000, -154.0000 ],
	[ 255.2000, -67.6000 ],
	[ 298.4000, -154.0000 ],
	[ 298.4000, -10.0000 ],
	[ 298.4000, 0.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_myPartH_faceLine_Fa000 = ctr_face_fig_myPartH_faceLine_Fa000_Ctr000;
fig_myPartH_faceLine = face_fig_myPartH_faceLine_Fa000;

const subpax_myPartH_circle =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartH_faceCircle )
		)
	);


const subpax_myPartH_line =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartH_faceLine )
		)
	);

const pax_myPartH = union( subpax_myPartH_circle, subpax_myPartH_line );

return pax_myPartH;
}
module.exports = { main };
