// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartW_faceTop_Fa000_Ctr000 = polygon({ points: [ [ -5.0000, 0.0000 ],
	[ 5.0000, 0.0000 ],
	[ 5.0000, 15.0000 ],
	[ -5.0000, 15.0000 ],
	[ -5.0000, 0.0000 ] ] });

const ctr_face_fig_myPartW_faceTop_Fa000_Ctr001 = polygon({ points: [ [ -4.8000, 0.2000 ],
	[ 4.8000, 0.2000 ],
	[ 4.8000, 14.8000 ],
	[ -4.8000, 14.8000 ],
	[ -4.8000, 0.2000 ] ] });

face_fig_myPartW_faceTop_Fa000 = subtract( ctr_face_fig_myPartW_faceTop_Fa000_Ctr000, ctr_face_fig_myPartW_faceTop_Fa000_Ctr001 );
fig_myPartW_faceTop = face_fig_myPartW_faceTop_Fa000;
const ctr_face_fig_myPartW_faceFace_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 8.0000 ],
	[ -6.0000, 3.2000 ],
	[ -5.8751, 3.0438 ],
	[ 0.0000, 7.7439 ],
	[ 5.8751, 3.0438 ],
	[ 6.0000, 3.2000 ],
	[ 0.0000, 8.0000 ] ] });

face_fig_myPartW_faceFace_Fa000 = ctr_face_fig_myPartW_faceFace_Fa000_Ctr000;
fig_myPartW_faceFace = face_fig_myPartW_faceFace_Fa000;

const subpax_myPartW_wall =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0.7853981633974483, ],
			   extrudeLinear( {height: 4}, fig_myPartW_faceTop )
		)
	);


const subpax_myPartW_roof =
	translate( [ -11.31370849898476, 11.313708498984761, 0, ],
		rotate( [ 1.5707963267948966, 0, 0.7853981633974483, ],
			   extrudeLinear( {height: 17}, fig_myPartW_faceFace )
		)
	);

const pax_myPartW = union( subpax_myPartW_wall, subpax_myPartW_roof );

return pax_myPartW;
}
module.exports = { main };
