// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartL_face1_Fa000_Ctr000 = polygon({ points: [ [ 15.0000, 0.0000 ],
	[ 28.2843, 10.0000 ],
	[ 3.5355, 3.5355 ],
	[ 10.0000, 28.2843 ],
	[ 0.0000, 15.0000 ],
	[ -10.0000, 28.2843 ],
	[ -3.5355, 3.5355 ],
	[ -28.2843, 10.0000 ],
	[ -15.0000, 0.0000 ],
	[ -28.2843, -10.0000 ],
	[ -3.5355, -3.5355 ],
	[ -10.0000, -28.2843 ],
	[ -0.0000, -15.0000 ],
	[ 10.0000, -28.2843 ],
	[ 3.5355, -3.5355 ],
	[ 28.2843, -10.0000 ],
	[ 15.0000, -0.0000 ] ] });

face_fig_myPartL_face1_Fa000 = ctr_face_fig_myPartL_face1_Fa000_Ctr000;
fig_myPartL_face1 = face_fig_myPartL_face1_Fa000;

const subpax_myPartL =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartL_face1 )
		)
	);

const pax_myPartL = subpax_myPartL;

return pax_myPartL;
}
module.exports = { main };
