// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartO_face1_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 40.0000, 0.0000 ],
	[ 40.9254, 1.7313 ],
	[ 41.7356, 3.5195 ],
	[ 42.4271, 5.3568 ],
	[ 42.9970, 7.2354 ],
	[ 43.4428, 9.1473 ],
	[ 43.7626, 11.0842 ],
	[ 43.9550, 13.0379 ],
	[ 44.0192, 15.0000 ],
	[ 43.9550, 16.9621 ],
	[ 43.7626, 18.9158 ],
	[ 43.4428, 20.8527 ],
	[ 42.9970, 22.7646 ],
	[ 42.4271, 24.6432 ],
	[ 41.7356, 26.4805 ],
	[ 40.9254, 28.2687 ],
	[ 40.0000, 30.0000 ],
	[ 39.0060, 31.5719 ],
	[ 37.8887, 33.0587 ],
	[ 36.6555, 34.4508 ],
	[ 35.3142, 35.7391 ],
	[ 33.8735, 36.9153 ],
	[ 32.3430, 37.9718 ],
	[ 30.7323, 38.9017 ],
	[ 29.0521, 39.6990 ],
	[ 27.3131, 40.3585 ],
	[ 25.5268, 40.8759 ],
	[ 23.7045, 41.2479 ],
	[ 21.8583, 41.4721 ],
	[ 20.0000, 41.5470 ],
	[ 18.1417, 41.4721 ],
	[ 16.2955, 41.2479 ],
	[ 14.4732, 40.8759 ],
	[ 12.6869, 40.3585 ],
	[ 10.9479, 39.6990 ],
	[ 9.2677, 38.9017 ],
	[ 7.6570, 37.9718 ],
	[ 6.1265, 36.9153 ],
	[ 4.6858, 35.7391 ],
	[ 3.3445, 34.4508 ],
	[ 2.1113, 33.0587 ],
	[ 0.9940, 31.5719 ],
	[ 0.0000, 30.0000 ],
	[ -0.9254, 28.2687 ],
	[ -1.7356, 26.4805 ],
	[ -2.4271, 24.6432 ],
	[ -2.9970, 22.7646 ],
	[ -3.4428, 20.8527 ],
	[ -3.7626, 18.9158 ],
	[ -3.9550, 16.9621 ],
	[ -4.0192, 15.0000 ],
	[ -3.9550, 13.0379 ],
	[ -3.7626, 11.0842 ],
	[ -3.4428, 9.1473 ],
	[ -2.9970, 7.2354 ],
	[ -2.4271, 5.3568 ],
	[ -1.7356, 3.5195 ],
	[ -0.9254, 1.7313 ],
	[ -0.0000, 0.0000 ] ] });

face_fig_myPartO_face1_Fa000 = ctr_face_fig_myPartO_face1_Fa000_Ctr000;
fig_myPartO_face1 = face_fig_myPartO_face1_Fa000;

const subpax_myPartO =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartO_face1 )
		)
	);

const pax_myPartO = subpax_myPartO;

return pax_myPartO;
}
module.exports = { main };
