// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_myPartL_face1_Fa000_Ctr000 = polygon({ points: [ [ 24.5000, 0.0000 ],
	[ 30.2603, 8.7500 ],
	[ 13.7886, 13.7886 ],
	[ 8.7500, 30.2603 ],
	[ 0.0000, 24.5000 ],
	[ -8.7500, 30.2603 ],
	[ -13.7886, 13.7886 ],
	[ -30.2603, 8.7500 ],
	[ -24.5000, 0.0000 ],
	[ -30.2603, -8.7500 ],
	[ -13.7886, -13.7886 ],
	[ -8.7500, -30.2603 ],
	[ -0.0000, -24.5000 ],
	[ 8.7500, -30.2603 ],
	[ 13.7886, -13.7886 ],
	[ 30.2603, -8.7500 ],
	[ 24.5000, -0.0000 ] ] });

face_fig_myPartL_face1_Fa000 = ctr_face_fig_myPartL_face1_Fa000_Ctr000;
fig_myPartL_face1 = face_fig_myPartL_face1_Fa000;

const subpax_myPartL =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_myPartL_face1 )
		)
	);

const pax_myPartL = subpax_myPartL;

return pax_myPartL;
}
module.exports = { main };
